apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/name: meshcommerce-observability
    app.kubernetes.io/part-of: meshcommerce
    istio-injection: disabled
