apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: meshcommerce
  labels:
    app.kubernetes.io/name: payments-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payments-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
