@TaskManagement.Api_HostAddress = http://localhost:5284
@TaskId = replace-with-task-id

GET {{TaskManagement.Api_HostAddress}}/health
Accept: application/json

###

GET {{TaskManagement.Api_HostAddress}}/tasks
Accept: application/json

###

GET {{TaskManagement.Api_HostAddress}}/tasks/{{TaskId}}
Accept: application/json

###

POST {{TaskManagement.Api_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "Study Kubernetes basics",
  "description": "Create the first task API before containerizing it."
}

###

DELETE {{TaskManagement.Api_HostAddress}}/tasks/{{TaskId}}
