server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://orders-api:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host orders-api;
        proxy_connect_timeout 2s;
        proxy_read_timeout 10s;
    }

    location = /mesh-lab/payments {
        proxy_pass http://payments-api:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host payments-api;
        proxy_connect_timeout 2s;
        proxy_read_timeout 5s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}