apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: payments-api-circuit-breaker
  namespace: meshcommerce
spec:
  host: payments-api.meshcommerce.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 1s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 0
