apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: meshcommerce
data:
  datasource.yaml: |
    apiVersion: 1
    prune: true
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 5s

  dashboard-provider.yaml: |
    apiVersion: 1
    providers:
      - name: meshcommerce
        orgId: 1
        folder: MeshCommerce
        folderUid: meshcommerce
        type: file
        disableDeletion: true
        allowUiUpdates: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/provisioned-dashboards
          foldersFromFilesStructure: false
