apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: meshcommerce
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meshcommerce-prometheus
  namespace: meshcommerce
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: meshcommerce
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meshcommerce-prometheus
  namespace: meshcommerce
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: meshcommerce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: meshcommerce-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: observability
