apiVersion: v1
kind: ConfigMap
metadata:
  name: task-management-api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  UseMockRepository: "true"
  CodigoUnico: "ABC-123"
