apiVersion: v1
kind: Secret
metadata:
  name: task-management-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=task_management;Username=task_user;Password=task_password
